export const  FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const  FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const  FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';
export const  FETCH_SINGLE_SUCCESS = 'FETCh_SINGLE_SUCCESS';
export const  FETCH_SINGLE_REQUEST = 'FETCH_SINGLE_REQUEST';
export const  FETCH_SINGLE_ERROR = 'FETCH_SINGLE_ERROR';

